from setuptools import setup, find_packages

setup(name='sonoUno',
      version='3.1.0',
      description='Data sonorization tool',
      url='http://github.com/sonounoteam/sonouno',
      author='Johanna Casado',
      author_email='johi.ceh@gmail.com',
      license='MIT',
      package_dir={"": "sonoUno"},
      packages= find_packages('sonoUno', exclude=['sample_data']),
      scripts=['sonoUno/sonoUno'],
      python_requires='>3.5.0',
      install_requires=[
        'cycler',
        'kiwisolver',
        'matplotlib',
        'numpy',
        'pandas',
        'Pillow',
        'pygame',
        'pyparsing',
        'python-dateutil',
        'pytz',
        'six',
        'oct2py',
        'wxpython',
      ],
      zip_safe=True)
